Repository ManagerTeamm/MockProject_062025_Nhom13, pull requests merged in 2025-07, with the labels that each got.

#96 fix report feature
  BackEnd_Api/Controllers/ReportController.cs
  BackEnd_Api/Migrations/20250708032455_Initial.Designer.cs
  BackEnd_Api/Migrations/20250708032455_Initial.cs
  BackEnd_Api/Migrations/ApplicationDbContextModelSnapshot.cs
  BackEnd_Api/wwwroot/files/evidence_20250708/evidence_008e0047-4649-4224-9e30-bf046288fad0_3d09ec31-4f6b-4d2a-892e-aebf653bf5ce.png
  FrontEnd_App/src/components/RelevantPartiesForm.jsx
  FrontEnd_App/src/components/initialEvidence.jsx
  FrontEnd_App/src/pages/reportSuspect.jsx
Labels: On-time

#98 Code SceneProtection Component
  BackEnd_Api/Controllers/CaseController.cs
  BackEnd_Api/Controllers/ReportController.cs
  BackEnd_Api/Controllers/UserController.cs
  BackEnd_Api/Models/Arrest.cs
  BackEnd_Api/Models/CaseEvidence.cs
  BackEnd_Api/Models/CaseResult.cs
  BackEnd_Api/Models/Event.cs
  BackEnd_Api/Models/Evidence.cs
  BackEnd_Api/Models/Indictment.cs
  BackEnd_Api/Models/Inmate.cs
  BackEnd_Api/Models/Interview.cs
  BackEnd_Api/Models/InvestigationPlan.cs
  BackEnd_Api/Models/Prosecution.cs
  BackEnd_Api/Models/ProsecutionSuspect.cs
  BackEnd_Api/Models/Question.cs
  BackEnd_Api/Models/RecordInfo.cs
  BackEnd_Api/Models/Report.cs
  BackEnd_Api/Models/ReportParties.cs
  BackEnd_Api/Models/SceneDescription.cs
  BackEnd_Api/Models/SceneMedia.cs
  BackEnd_Api/Models/SceneProtection.cs
  BackEnd_Api/Models/SceneSuport.cs
  BackEnd_Api/Models/Sentence.cs
  BackEnd_Api/Models/SuspectEvidence.cs
  BackEnd_Api/Models/Timeline.cs
  BackEnd_Api/Models/UserCase.cs
  BackEnd_Api/Models/Warrant.cs
  BackEnd_Api/Models/WarrantResult.cs
  BackEnd_Api/Repositories/CaseRepository.cs
  BackEnd_Api/Repositories/Interfaces/ICaseRepository.cs
  FrontEnd_App/package-lock.json
  FrontEnd_App/package.json
  FrontEnd_App/src/components/PatrolOfficerManagement.jsx
  FrontEnd_App/src/components/fileUploader.jsx
  FrontEnd_App/src/components/sceneProtectionForm.jsx
  FrontEnd_App/src/components/sidebar.jsx
  FrontEnd_App/src/index.jsx
  FrontEnd_App/src/models/sceneProtection.js
  FrontEnd_App/src/routes/routes.jsx
  FrontEnd_App/src/services/caseService.js
  FrontEnd_App/src/services/userService.js
  FrontEnd_App/src/styles/sceneProtection.css
Labels: Task

#117 Ho van thanh
  BackEnd_Api/Attributes/HasPermissionAttribute.cs
  BackEnd_Api/Attributes/HasPermissionFilter.cs
  BackEnd_Api/Controllers/CaseController.cs
  BackEnd_Api/Dtos/Cases/CaseDto.cs
  BackEnd_Api/Dtos/Cases/InitialResponseDto.cs
  BackEnd_Api/Repositories/Interfaces/ISceneProtectionRepository.cs
  BackEnd_Api/Repositories/Interfaces/ISceneSupportRepository.cs
  BackEnd_Api/Repositories/SceneProtectionRepository.cs
  BackEnd_Api/Repositories/SceneSupportRepository.cs
  BackEnd_Api/Repositories/SuspectRepository.cs
  FrontEnd_App/package.json
  FrontEnd_App/src/components/MedicalSupportForm.jsx
  FrontEnd_App/src/components/PatrolOfficerManagement.jsx
  FrontEnd_App/src/components/fileUploader.jsx
  FrontEnd_App/src/components/initialResponse.jsx
  FrontEnd_App/src/components/navbarphase2.jsx
  FrontEnd_App/src/components/panel/medicalsupport.jsx
  FrontEnd_App/src/components/sceneProtectionForm.jsx
  FrontEnd_App/src/css/PatrolOfficerManagement.module.css
  FrontEnd_App/src/css/navbarphase2.module.css
  FrontEnd_App/src/pages/caseList.jsx
  FrontEnd_App/src/routes/routes.jsx
  FrontEnd_App/src/samples/medical.jsx
  FrontEnd_App/src/services/userService.js
  FrontEnd_App/src/styles/MedicalSupportForm.module.css
Labels: On-time

#126 Done InitialResponse feature. Fixed some bugs
  BackEnd_Api/Controllers/CaseController.cs
  BackEnd_Api/Dtos/Cases/InitialResponseDto.cs
  BackEnd_Api/Migrations/20250712011324_Initial.Designer.cs
  BackEnd_Api/Migrations/20250712011324_Initial.cs
  BackEnd_Api/Migrations/ApplicationDbContextModelSnapshot.cs
  BackEnd_Api/Models/ApplicationDbContext.cs
  BackEnd_Api/Models/InitialResponse.cs
  BackEnd_Api/Models/MedicalRescueSupport.cs
  BackEnd_Api/Models/MedicalRescueSupportAttachment.cs
  BackEnd_Api/Models/ScenePreservationMeasure.cs
  BackEnd_Api/Models/ScenePreservationMeasureAttachment.cs
  BackEnd_Api/Program.cs
  BackEnd_Api/Repositories/InitialResponseRepository.cs
  BackEnd_Api/Repositories/Interfaces/IInitialResponseRepository.cs
  BackEnd_Api/Repositories/Interfaces/IMedicalRescueSupportAttachmentRepository.cs
  BackEnd_Api/Repositories/Interfaces/IMedicalRescueSupportRepository.cs
  BackEnd_Api/Repositories/Interfaces/IRepository.cs
  BackEnd_Api/Repositories/Interfaces/IScenePreservationMeasureAttachmentRepository.cs
  BackEnd_Api/Repositories/Interfaces/IScenePreservationMeasureRepository.cs
  BackEnd_Api/Repositories/Interfaces/ISceneProtectionRepository.cs
  BackEnd_Api/Repositories/Interfaces/ISceneSupportRepository.cs
  BackEnd_Api/Repositories/Interfaces/IUnitOfWork.cs
  BackEnd_Api/Repositories/Interfaces/IUserCaseRepository.cs
  BackEnd_Api/Repositories/MedicalRescueSupportAttachmentRepository.cs
  BackEnd_Api/Repositories/MedicalRescueSupportRepository.cs
  BackEnd_Api/Repositories/Repository.cs
  BackEnd_Api/Repositories/ScenePreservationMeasureAttachmentRepository.cs
  BackEnd_Api/Repositories/ScenePreservationMeasureRepository.cs
  BackEnd_Api/Repositories/SceneProtectionRepository.cs
  BackEnd_Api/Repositories/SceneSupportRepository.cs
  BackEnd_Api/Repositories/UnitOfWork.cs
  BackEnd_Api/Repositories/UserCaseRepository.cs
  FrontEnd_App/src/components/MedicalSupportForm.jsx
  FrontEnd_App/src/components/RelevantPartiesForm.jsx
  FrontEnd_App/src/components/caseDetailStep2/initialStatement.jsx
  FrontEnd_App/src/components/howYouCanHelp.jsx
  FrontEnd_App/src/components/initialEvidence.jsx
  FrontEnd_App/src/components/initialResponse.jsx
  FrontEnd_App/src/components/panel/initialstatement.jsx
  FrontEnd_App/src/components/sceneProtectionForm.jsx
  FrontEnd_App/src/pages/reportSuspect.jsx
  FrontEnd_App/src/samples/viewInitialStatement.jsx
  FrontEnd_App/src/services/caseService.js
  FrontEnd_App/src/styles/initialstatement.css
  FrontEnd_App/src/styles/initialstatement.module.css
Labels: Fixed
